detector_nodes:
# Keep in mind to tab-align the values!!!!
# The name of the detector MUST be the same as the field inside the DetectionArray message!
  - 
    name:           "head"
    min_detections: 0
    weight:         1
    min_frequency:  2
    topic:          "/people_detection_sensorring/detection_tracker/face_position_array"
  - 
    name:           "laser"
    min_detections: 1
    weight:         1
    min_frequency:  2
    topic:          "/people_detections/laser_detections"
time_horizon_sec: 0.4
