; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude FaceDetectorFeedback.msg.html

(cl:defclass <FaceDetectorFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass FaceDetectorFeedback (<FaceDetectorFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FaceDetectorFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FaceDetectorFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<FaceDetectorFeedback> is deprecated: use cob_people_detection-msg:FaceDetectorFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FaceDetectorFeedback>) ostream)
  "Serializes a message object of type '<FaceDetectorFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FaceDetectorFeedback>) istream)
  "Deserializes a message object of type '<FaceDetectorFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FaceDetectorFeedback>)))
  "Returns string type for a message object of type '<FaceDetectorFeedback>"
  "cob_people_detection/FaceDetectorFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FaceDetectorFeedback)))
  "Returns string type for a message object of type 'FaceDetectorFeedback"
  "cob_people_detection/FaceDetectorFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FaceDetectorFeedback>)))
  "Returns md5sum for a message object of type '<FaceDetectorFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FaceDetectorFeedback)))
  "Returns md5sum for a message object of type 'FaceDetectorFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FaceDetectorFeedback>)))
  "Returns full string definition for message of type '<FaceDetectorFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FaceDetectorFeedback)))
  "Returns full string definition for message of type 'FaceDetectorFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FaceDetectorFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FaceDetectorFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FaceDetectorFeedback
))
