; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude FaceDetectorGoal.msg.html

(cl:defclass <FaceDetectorGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass FaceDetectorGoal (<FaceDetectorGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FaceDetectorGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FaceDetectorGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<FaceDetectorGoal> is deprecated: use cob_people_detection-msg:FaceDetectorGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FaceDetectorGoal>) ostream)
  "Serializes a message object of type '<FaceDetectorGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FaceDetectorGoal>) istream)
  "Deserializes a message object of type '<FaceDetectorGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FaceDetectorGoal>)))
  "Returns string type for a message object of type '<FaceDetectorGoal>"
  "cob_people_detection/FaceDetectorGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FaceDetectorGoal)))
  "Returns string type for a message object of type 'FaceDetectorGoal"
  "cob_people_detection/FaceDetectorGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FaceDetectorGoal>)))
  "Returns md5sum for a message object of type '<FaceDetectorGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FaceDetectorGoal)))
  "Returns md5sum for a message object of type 'FaceDetectorGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FaceDetectorGoal>)))
  "Returns full string definition for message of type '<FaceDetectorGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FaceDetectorGoal)))
  "Returns full string definition for message of type 'FaceDetectorGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FaceDetectorGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FaceDetectorGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FaceDetectorGoal
))
