; Auto-generated. Do not edit!


(cl:in-package cob_people_detection-msg)


;//! \htmlinclude FaceDetectorResult.msg.html

(cl:defclass <FaceDetectorResult> (roslisp-msg-protocol:ros-message)
  ((face_positions
    :reader face_positions
    :initarg :face_positions
    :type (cl:vector people_msgs-msg:PositionMeasurement)
   :initform (cl:make-array 0 :element-type 'people_msgs-msg:PositionMeasurement :initial-element (cl:make-instance 'people_msgs-msg:PositionMeasurement))))
)

(cl:defclass FaceDetectorResult (<FaceDetectorResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FaceDetectorResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FaceDetectorResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_people_detection-msg:<FaceDetectorResult> is deprecated: use cob_people_detection-msg:FaceDetectorResult instead.")))

(cl:ensure-generic-function 'face_positions-val :lambda-list '(m))
(cl:defmethod face_positions-val ((m <FaceDetectorResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_people_detection-msg:face_positions-val is deprecated.  Use cob_people_detection-msg:face_positions instead.")
  (face_positions m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FaceDetectorResult>) ostream)
  "Serializes a message object of type '<FaceDetectorResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'face_positions))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'face_positions))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FaceDetectorResult>) istream)
  "Deserializes a message object of type '<FaceDetectorResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'face_positions) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'face_positions)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'people_msgs-msg:PositionMeasurement))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FaceDetectorResult>)))
  "Returns string type for a message object of type '<FaceDetectorResult>"
  "cob_people_detection/FaceDetectorResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FaceDetectorResult)))
  "Returns string type for a message object of type 'FaceDetectorResult"
  "cob_people_detection/FaceDetectorResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FaceDetectorResult>)))
  "Returns md5sum for a message object of type '<FaceDetectorResult>"
  "b5dc843df183dbab7f0ab2f5ef5b6f9d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FaceDetectorResult)))
  "Returns md5sum for a message object of type 'FaceDetectorResult"
  "b5dc843df183dbab7f0ab2f5ef5b6f9d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FaceDetectorResult>)))
  "Returns full string definition for message of type '<FaceDetectorResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%people_msgs/PositionMeasurement[] face_positions~%~%================================================================================~%MSG: people_msgs/PositionMeasurement~%Header          header~%string          name~%string          object_id~%geometry_msgs/Point  pos~%float64         reliability~%float64[9]      covariance~%byte            initialization~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FaceDetectorResult)))
  "Returns full string definition for message of type 'FaceDetectorResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%people_msgs/PositionMeasurement[] face_positions~%~%================================================================================~%MSG: people_msgs/PositionMeasurement~%Header          header~%string          name~%string          object_id~%geometry_msgs/Point  pos~%float64         reliability~%float64[9]      covariance~%byte            initialization~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FaceDetectorResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'face_positions) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FaceDetectorResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FaceDetectorResult
    (cl:cons ':face_positions (face_positions msg))
))
